import React from 'react';
import { AVATARS } from '../../constants/studentConstants';

export function StudentLogin({ go, selectedAvatar, setSelectedAvatar, onLogin }) {
  return <>
    <div className="top-nav login-top-nav login-student-nav"><button className="btn btn-outline btn-sm" onClick={() => go('screen-home')}>← Home</button><div className="logo">🎒 Student Login</div><div className="login-nav-pill">⭐ Tuklas. Matuto. Magsaya!</div></div>
    <div className="login-stage student-stage"><div className="login-shell student-shell">
      <aside className="login-visual-card student-visual-card"><div className="login-sparkles">✦</div><h2>Mag-login,<br />Estudyante! 👋</h2><p>Piliin ang avatar mo at ilagay ang Student ID para magpatuloy.</p><div className="student-hero-illustration login-hero-png-wrap" aria-hidden="true"><img src="/login-student-girl.png" alt="" className="login-hero-png student" /></div><div className="login-info-card"><span className="info-icon">🛡️</span><div><b>Ligtas • Masaya • Makabuluhan</b><br /><span>Tuklas Talino, kasama mo sa bawat hakbang.</span></div></div></aside>
      <section className="login-form-panel student-form-panel"><div className="login-form-heading"><span className="heading-badge">👤</span><div><h3>Pumili ng Avatar</h3><p>Piliin ang avatar na gusto mong gamitin.</p></div></div><div className="avatar-grid avatar-grid-v2" id="stu-avatar-grid">{AVATARS.map(a => <button type="button" className={`avatar-circle ${selectedAvatar === a ? 'selected' : ''}`} onClick={() => setSelectedAvatar(a)} key={a}>{a}</button>)}</div><div className="login-divider" /><label className="login-label" htmlFor="stu-id">🪪 Student ID</label><div className="input-with-icon"><span>👤</span><input className="input-field" id="stu-id" placeholder="Halimbawa: STU-2025-001" /><span className="input-check">✓</span></div><label className="login-label" htmlFor="stu-password">🔒 Password</label><div className="input-with-icon"><span>🔐</span><input className="input-field" id="stu-password" placeholder="Default: student123" type="password" /></div><button className="btn btn-green login-main-btn" onClick={onLogin}>✨ Login</button><p className="secure-note">🔒 Ang iyong impormasyon ay ligtas at protektado.</p></section>
    </div><div className="login-tip-card">💡 <b>Tip:</b> Demo password ng students: <strong>student123</strong>. <span>💚</span></div></div>
  </>;
}

export function TeacherLogin({ go, onLogin }) {
  return <><div className="top-nav login-top-nav login-teacher-nav"><button className="btn btn-outline btn-sm" onClick={() => go('screen-home')}>← Home</button><div className="logo">👩‍🏫 Teacher Login</div><div className="login-nav-pill teacher-pill">⭐ Salamat sa dedikasyon, Guro!</div></div><div className="login-stage teacher-stage"><div className="login-shell teacher-shell"><aside className="login-visual-card teacher-visual-card"><h2>Inspire<br />Educate<br />Empower</h2><div className="teacher-hero-illustration login-hero-png-wrap" aria-hidden="true"><img src="/landing-teacher.png" alt="" className="login-hero-png teacher" /></div><div className="login-info-card"><span className="info-icon">👥</span><div><b>Tuklas Talino para sa mga Guro</b><br /><span>Pamahalaan ang klase, gumawa ng aralin, at subaybayan ang progreso.</span></div></div></aside><section className="login-form-panel teacher-form-panel"><h2>Mag-login, Guro!</h2><p className="login-subtitle">Gamitin ang iyong teacher username at password.</p><div className="login-divider" /><label className="login-label" htmlFor="t-username">👤 Username</label><div className="input-with-icon"><span>👤</span><input className="input-field" id="t-username" placeholder="Enter your username" /></div><label className="login-label" htmlFor="t-password">🔒 Password</label><div className="input-with-icon"><span>🔐</span><input className="input-field" id="t-password" placeholder="Enter your password" type="password" /></div><button className="btn btn-green login-main-btn teacher-login-btn" onClick={onLogin}>🔐 Login</button><div className="secure-login-strip">🛡️ Secure & Protected Login</div></section></div><div className="login-feature-row teacher-feature-row"><div><span>👥</span><b>Manage Classes</b><p>Pamahalaan ang klase at grupo.</p></div><div><span>📖</span><b>Create Lessons</b><p>Gumawa at magbahagi ng aralin.</p></div><div><span>📊</span><b>Track Progress</b><p>Subaybayan ang pag-unlad.</p></div><div><span>🏅</span><b>Inspire & Guide</b><p>Gabay sa pagkatuto.</p></div></div></div></>;
}

export function AdminLogin({ go, onLogin }) {
  return <><div className="top-nav login-top-nav login-admin-nav"><button className="btn btn-outline btn-sm" onClick={() => go('screen-home')}>← Home</button><div className="logo admin-logo">🛡️ Admin Login</div><div className="login-nav-pill admin-pill">🛡️ Secure Access • Protected System 🔒</div></div><div className="login-stage admin-stage"><div className="login-shell admin-shell"><aside className="login-visual-card admin-visual-card"><h2>Mag-login,<br />Admin!</h2><p>Gamitin ang admin username at password para magpatuloy.</p><div className="admin-hero-illustration login-hero-png-wrap" aria-hidden="true"><img src="/landing-admin.png" alt="" className="login-hero-png admin" /></div><div className="login-info-card admin-info-card"><span className="info-icon">🔐</span><div><b>Secure & Trusted</b><br /><span>Ang impormasyon at settings ay protektado.</span></div></div></aside><section className="login-form-panel admin-form-panel"><div className="admin-icon-top">🛡️</div><h2>Welcome Back, Admin</h2><div className="admin-underline" /><label className="login-label" htmlFor="a-username">Username</label><div className="input-with-icon admin-input"><span>👤</span><input className="input-field" id="a-username" placeholder="Enter your username" /></div><label className="login-label" htmlFor="a-password">Password</label><div className="input-with-icon admin-input"><span>🔒</span><input className="input-field" id="a-password" placeholder="Enter your password" type="password" /></div><button className="btn btn-purple login-main-btn admin-login-btn" onClick={onLogin}>🔐 Login</button><div className="secure-login-strip admin-secure-strip">🛡️ Secure Login</div><p className="secure-note">🔒 Only authorized administrators can access this system.</p></section></div></div></>;
}
